export const markets = [
  {
    company: "SpaceX",
    type: "OFFER",
    price: {
      value: "$194.5",
      total: "$368.0B (est.)",
      market: "-22% vs Market _ 5% vs Last",
    },
    size: "$7.8M",
    structure: "SPV (1/20)",
    share_class: "Unknown",
    source: "Top Broker",
    updated: "Today",
    submitted: "1/21/2025",
    actions: "",
  },
  {
    company: "Stripe",
    type: "BID",
    price: {
      value: "$65",
      total: "$165.0B",
      market: "-15% vs Market _ -25% vs Last",
    },
    size: "$2.5M",
    structure: "Direct",
    share_class: "Common",
    source: "Verified Seller",
    updated: "Yesterday",
    submitted: "1/20/2025",
    actions: "",
  },
  {
    company: "Databricks",
    type: "OFFER",
    price: {
      value: "$110.75",
      total: "$43.5B",
      market: "8% vs Market _ 12% vs Last",
    },
    size: "$5.0M",
    structure: "Direct",
    share_class: "Preferred",
    source: "Platform",
    updated: "2 days ago",
    submitted: "1/19/2025",
    actions: "",
  },
  {
    company: "Plaid",
    type: "BID",
    price: {
      value: "$45.25",
      total: "$13.2B",
      market: "-5% vs Market _ -10% vs Last",
    },
    size: "$1.2M",
    structure: "SPV (1/10)",
    share_class: "Common",
    source: "Top Broker",
    updated: "3 days ago",
    submitted: "1/18/2025",
    actions: "",
  },
  {
    company: "Anthropic",
    type: "OFFER",
    price: {
      value: "$85",
      total: "$4.1B",
      market: "15% vs Market _ 20% vs Last",
    },
    size: "$3.5M",
    structure: "Direct",
    share_class: "Preferred",
    source: "Verified Seller",
    updated: "4 days ago",
    submitted: "1/17/2025",
    actions: "",
  },
  {
    company: "Notion",
    type: "OFFER",
    price: {
      value: "$55.25",
      total: "$10.5B",
      market: "12% vs Market _ -8% vs Last",
    },
    size: "$4.2M",
    structure: "Direct",
    share_class: "Common",
    source: "Verified Seller",
    updated: "Today",
    submitted: "1/22/2025",
    actions: "",
  },
  {
    company: "Rippling",
    type: "BID",
    price: {
      value: "$92.75",
      total: "$11.8B",
      market: "-3% vs Market _ 15% vs Last",
    },
    size: "$2.8M",
    structure: "SPV (1/15)",
    share_class: "Preferred",
    source: "Top Broker",
    updated: "2 days ago",
    submitted: "1/20/2025",
    actions: "",
  },
  {
    company: "Scale AI",
    type: "OFFER",
    price: {
      value: "$145.5",
      total: "$7.2B",
      market: "8% vs Market _ -12% vs Last",
    },
    size: "$5.5M",
    structure: "Direct",
    share_class: "Common",
    source: "Platform",
    updated: "Today",
    submitted: "1/22/2025",
    actions: "",
  },
  {
    company: "Vercel",
    type: "BID",
    price: {
      value: "$78.25",
      total: "$6.5B",
      market: "-5% vs Market _ 10% vs Last",
    },
    size: "$3.1M",
    structure: "Direct",
    share_class: "Preferred",
    source: "Verified Seller",
    updated: "Yesterday",
    submitted: "1/21/2025",
    actions: "",
  },
];
