export const trades = [
  {
    company: "Kraken",
    type: "CLOSED TRADE",
    closed_Date: "January 21, 2025",
    upload_Date: "January 21, 2025",
    price_Per_Share: "$18.50",
    "Est. valuation": "$3.7B val. (est.)",
    price_Vs_Last_Round: "-97%",
    price_Vs_Market_Price: "-2%",
    volume: "$3.2M",
    structure: "Direct",
    shareClass: "Common",
  },
  {
    company: "Dataminr",
    type: "CLOSED TRADE",
    closed_Date: "January 16, 2025",
    upload_Date: "January 17, 2025",
    price_Per_Share: "$14.00",
    "Est. valuation": "$1.3B val. (est.)",
    price_Vs_Last_Round: "+6%",
    price_Vs_Market_Price: "-",
    volume: "$700.0K",
    structure: "Direct",
    shareClass: "Common",
  },
  {
    company: "SambaNova Systems",
    type: "CLOSED TRADE",
    closed_Date: "January 13, 2025",
    upload_Date: "January 14, 2025",
    price_Per_Share: "$29.00",
    "Est. valuation": "$1.5B val. (est.)",
    price_Vs_Last_Round: "-17%",
    price_Vs_Market_Price: "-",
    volume: "$800.0K",
    structure: "Direct",
    shareClass: "Common",
  },
  {
    company: "Redwood Materials",
    type: "CLOSED TRADE",
    closed_Date: "January 10, 2025",
    upload_Date: "January 14, 2025",
    price_Per_Share: "$52.00",
    "Est. valuation": "$5.4B val. (est.)",
    price_Vs_Last_Round: "+9%",
    price_Vs_Market_Price: "+3%",
    volume: "$2.5M",
    structure: "Direct",
    shareClass: "Preferred",
  },
  {
    company: "Cohere",
    type: "CLOSED TRADE",
    closed_Date: "January 8, 2025",
    upload_Date: "January 8, 2025",
    price_Per_Share: "$153.77",
    "Est. valuation": "$4.0B val. (est.)",
    price_Vs_Last_Round: "-27%",
    price_Vs_Market_Price: "-8%",
    volume: "$840.0K",
    structure: "Direct",
    shareClass: "Common",
  },
  {
    company: "Kin",
    type: "CLOSED TRADE",
    closed_Date: "January 6, 2025",
    upload_Date: "January 14, 2025",
    price_Per_Share: "$38.00",
    "Est. valuation": "$632.0M val. (est.)",
    price_Vs_Last_Round: "-37%",
    price_Vs_Market_Price: "-",
    volume: "$235.0K",
    structure: "Direct",
    shareClass: "Common",
  },
  {
    company: "xAI",
    type: "CLOSED TRADE",
    closed_Date: "January 3, 2025",
    upload_Date: "January 14, 2025",
    price_Per_Share: "$23.82",
    "Est. valuation": "$55.0B val. (est.)",
    price_Vs_Last_Round: "+10%",
    price_Vs_Market_Price: "-38%",
    volume: "$750.0K",
    structure: "SPV (0/15) (⚡)",
    shareClass: "Preferred",
  },
  {
    company: "Grog",
    type: "CLOSED TRADE",
    closed_Date: "December 31, 2024",
    upload_Date: "January 6, 2025",
    price_Per_Share: "$16.40",
    "Est. valuation": "$2.9B val. (est.)",
    price_Vs_Last_Round: "+2%",
    price_Vs_Market_Price: "+0%",
    volume: "$16.0M",
    structure: "SPV (0/0) (⚡)",
    shareClass: "Common",
  },
  {
    company: "CoreWeave",
    type: "CLOSED TRADE",
    closed_Date: "December 28, 2024",
    upload_Date: "January 8, 2025",
    price_Per_Share: "$1050.00",
    "Est. valuation": "$25.7B val. (est.)",
    price_Vs_Last_Round: "+12%",
    price_Vs_Market_Price: "-16%",
    volume: "$430.5K",
    structure: "Direct",
    shareClass: "Common",
  },
  {
    company: "Klarna",
    type: "CLOSED TRADE",
    closed_Date: "December 25, 2024",
    upload_Date: "January 7, 2025",
    price_Per_Share: "$500.00",
    "Est. valuation": "$15.2B val. (est.)",
    price_Vs_Last_Round: "+5%",
    price_Vs_Market_Price: "-",
    volume: "$5.0M",
    structure: "Direct",
    shareClass: "Common",
  },
  {
    company: "SpaceX",
    type: "CLOSED TRADE",
    closed_Date: "December 24, 2024",
    upload_Date: "December 27, 2024",
    price_Per_Share: "$128.00",
    "Est. valuation": "$242.2B val. (est.)",
    price_Vs_Last_Round: "-31%",
    price_Vs_Market_Price: "-49%",
    volume: "$100.0K",
    structure: "SPV (0/15) (⚡)",
    shareClass: "Preferred",
  },
  {
    company: "Epic Games",
    type: "CLOSED TRADE",
    closed_Date: "December 23, 2024",
    upload_Date: "December 24, 2024",
    price_Per_Share: "$435.00",
    "Est. valuation": "$16.3B val. (est.)",
    price_Vs_Last_Round: "-28%",
    price_Vs_Market_Price: "-1%",
    volume: "$1.5M",
    structure: "Direct",
    shareClass: "Common",
  },
];
